[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    pubsubclient
    DHT sensor library
    Wire

build_flags =
    -Iinclude
    -DIS_PRODUCTION=0

monitor_speed = 115200

[env:esp32dev_prod]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    pubsubclient
    DHT sensor library
    Wire

build_flags =
    -Iinclude
    -DIS_PRODUCTION=1

monitor_speed = 115200
